language: go

sudo: false

cache:
  directories:
    $HOME/.ccm/repository

matrix:
  fast_finish: true

env:
- CASS=1.2.19
- CASS=2.0.12
- CASS=2.1.2

go:
  - 1.3
  - 1.4

install:
  - pip install --user cql PyYAML six
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - git clone https://github.com/pcmanus/ccm.git
  - pushd ccm
  - ./setup.py install --user
  - popd
  - go get .

script:
  - set -e
  - go test -v -tags unit
  - PATH=$PATH:$HOME/.local/bin bash -x integration.sh $CASS
  - go vet .

notifications:
  - email: false
